# Spring
server:
  port: 8080
spring:
  profiles:
    active: test
# Wechat
wechat:
  url: ws://192.168.1.1:5555
  botnick: 微信bot昵称
  botwxid: wxid_xxxxxxxxx

# Redis
redis:
  database: 0
  host: 192.168.1.1
  port: 6379
  password: 12345
  timeout: 3000